# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru/
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

server:
  port: 443
  ssl:
    key-store: /etc/letsencrypt/live/creazione.ru/keystore.p12
    key-store-password: HJKGF576..HJKHjer8586hfkjJU7%gllGrwdKK
    keyStoreType: PKCS12
    keyAlias: tomcat
  http:
    port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost/search_engine
    username: door
    password: door
  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: none