# example values

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru/
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost/search_engine
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none